package service

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"mime"
	"mime/multipart"
	"net/http"
	"net/textproto"
	"path"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/tigerowo/infinite-canvas/model"
)

const ModelChannelProtocolRunningHub = "runninghub"

// runninghub_registry.json is generated by scripts/runninghub-registry.mjs from the official RunningHub model registry.
//
//go:embed runninghub_registry.json
var runningHubRegistryJSON []byte

var runningHubMediaLabels = map[string]string{"first": "首帧", "last": "尾帧", "images": "参考图", "videos": "参考视频", "audios": "参考音频"}

// RunningHubLipSyncModel chains Kling face identification, optional Kling TTS and lip-sync-video in one request.
const RunningHubLipSyncModel = "kling-lip-sync/video"

// runningHubResultExtensions lists preferred result files per output kind, since tasks can also return previews and covers.
var runningHubResultExtensions = map[string][]string{
	"audio":   {".mp3", ".wav", ".flac", ".m4a", ".aac", ".ogg", ".opus"},
	"model3d": {".glb", ".gltf", ".usdz", ".obj", ".fbx", ".stl"},
}

// runningHubPollInterval follows the RunningHub API contract's 5-second polling guidance.
var runningHubPollInterval = 5 * time.Second

type runningHubParam struct {
	Key      string   `json:"key"`
	Type     string   `json:"type"`
	Use      string   `json:"use"`
	Required bool     `json:"required"`
	Default  any      `json:"default"`
	Options  []any    `json:"options"`
	Min      *float64 `json:"min"`
	Max      *float64 `json:"max"`
	Step     *float64 `json:"step"`
	Limit    int      `json:"limit"`
	Multiple bool     `json:"multiple"`
}

type runningHubRegistryData struct {
	// Families maps `<family>/video|image|tts` to input modes and their candidate endpoints in preference order.
	Families  map[string]map[string][]string `json:"families"`
	Endpoints map[string][]runningHubParam   `json:"endpoints"`
}

var runningHubRegistry = sync.OnceValue(func() runningHubRegistryData {
	var registry runningHubRegistryData
	if err := json.Unmarshal(runningHubRegistryJSON, &registry); err != nil {
		panic("invalid RunningHub registry: " + err.Error())
	}
	return registry
})

// RunningHubMedia is one request input: a URL, or file bytes that are uploaded to RunningHub first.
type RunningHubMedia struct {
	URL         string
	Data        []byte
	Filename    string
	ContentType string
}

// RunningHubInputs are the OpenAI-shaped request values mapped onto a RunningHub endpoint schema.
type RunningHubInputs struct {
	Prompt        string
	Size          string // ratio such as 16:9 or adaptive, or WxH pixels
	Resolution    string // video level such as 720p or 2k
	Quality       string
	Seconds       string
	GenerateAudio string
	Voice         string
	Count         int
	Speed         float64
	// AudioDurationMs is the reference audio length, needed to trim audio for lip sync.
	AudioDurationMs int
	Media           map[string][]RunningHubMedia // keyed by runningHubMediaLabels roles
	// Extra holds advanced parameters from the settings panel, keyed by schema field.
	Extra map[string]any
}

type RunningHubTask struct {
	TaskID string
	Status string // queued, processing, completed or failed
	URLs   []string
	Text   string   // first non-URL text result, e.g. lyrics, captions or JSON from helper endpoints
	Texts  []string // every non-URL text result; helper endpoints split facts such as session and face across them
	Error  string
	Raw    []byte
}

func IsRunningHubChannel(channel model.ModelChannel) bool {
	return strings.EqualFold(strings.TrimSpace(channel.Protocol), ModelChannelProtocolRunningHub)
}

func RunningHubModels() []string {
	models := make([]string, 0, len(runningHubRegistry().Families))
	for name := range runningHubRegistry().Families {
		models = append(models, name)
	}
	sort.Strings(models)
	return models
}

func runningHubBaseURL(channel model.ModelChannel) string {
	baseURL := normalizeModelChannelBaseURL(channel.BaseURL)
	if !strings.HasSuffix(strings.ToLower(baseURL), "/openapi/v2") {
		baseURL += "/openapi/v2"
	}
	return baseURL
}

// SelectRunningHubEndpoint picks the first family endpoint for the input mode whose media fields accept every input.
func SelectRunningHubEndpoint(modelName string, media map[string][]RunningHubMedia) (string, error) {
	modelName = strings.TrimSpace(modelName)
	modes, ok := runningHubRegistry().Families[modelName]
	if !ok {
		return "", fmt.Errorf("RunningHub 暂不支持模型 %s", modelName)
	}
	mode := "text"
	switch {
	case len(media["first"])+len(media["last"]) > 0:
		mode = "frames"
	case strings.HasSuffix(modelName, "/image") && len(media["images"]) > 0:
		mode = "edit"
	case len(media["images"])+len(media["videos"])+len(media["audios"]) > 0:
		mode = "reference"
	}
	for _, endpoint := range modes[mode] {
		if runningHubEndpointFits(runningHubRegistry().Endpoints[endpoint], media) {
			return endpoint, nil
		}
	}
	// Name the missing required media: of the chosen mode, or of any mode when only a prompt was given.
	candidates := modes[mode]
	if mode == "text" {
		candidates = append(append(append([]string{}, modes["frames"]...), modes["reference"]...), modes["edit"]...)
	}
	for _, endpoint := range candidates {
		for _, param := range runningHubRegistry().Endpoints[endpoint] {
			if label := runningHubMediaLabels[param.Use]; label != "" && param.Required && len(media[param.Use]) == 0 {
				return "", errors.New("该模型需要" + label)
			}
		}
	}
	if len(modes[mode]) > 0 {
		return "", fmt.Errorf("素材数量或组合不符合该模型要求：首帧 %d、尾帧 %d、参考图 %d、参考视频 %d、参考音频 %d", len(media["first"]), len(media["last"]), len(media["images"]), len(media["videos"]), len(media["audios"]))
	}
	return "", errors.New(map[string]string{"text": "该模型不支持纯文本生成，请添加首帧或参考素材", "frames": "该模型不支持首尾帧", "reference": "该模型不支持参考素材", "edit": "该模型不支持参考图"}[mode])
}

func runningHubEndpointFits(params []runningHubParam, media map[string][]RunningHubMedia) bool {
	capacity := map[string]int{}
	for _, param := range params {
		if runningHubMediaLabels[param.Use] == "" {
			continue
		}
		if param.Required && len(media[param.Use]) == 0 {
			return false
		}
		capacity[param.Use] += max(param.Limit, 1)
	}
	for use, items := range media {
		if len(items) > capacity[use] {
			return false
		}
	}
	return true
}

// BuildRunningHubPayload maps advanced parameters and inputs onto the endpoint schema. Required fields without a value
// use the schema default, except free-text fields whose defaults are only samples.
func BuildRunningHubPayload(endpoint string, inputs RunningHubInputs) ([]byte, error) {
	params := runningHubRegistry().Endpoints[endpoint]
	payload := map[string]any{}
	used := map[string]int{}
	_, _, hasDims := runningHubDims(inputs.Size)
	sizedByPixels := false
	for _, param := range params {
		sizedByPixels = sizedByPixels || hasDims && param.Use == "width"
	}
	for _, param := range params {
		if param.Use == "prompt" && param.Required && strings.TrimSpace(inputs.Prompt) == "" {
			return nil, errors.New("请输入提示词")
		}
		value, ok := runningHubExtraValue(param, inputs.Extra[param.Key])
		if !ok {
			value = runningHubParamValue(param, inputs, used, sizedByPixels)
		}
		if value == nil && param.Required && (param.Use != "" || param.Type != "STRING") {
			value = param.Default
		}
		if value == nil {
			if param.Required {
				return nil, fmt.Errorf("请填写参数 %s", param.Key)
			}
			continue
		}
		payload[param.Key] = value
	}
	return json.Marshal(payload)
}

// runningHubExtraValue converts an advanced parameter to the schema type; ok is false when unset, invalid or a media field.
func runningHubExtraValue(param runningHubParam, raw any) (any, bool) {
	text := strings.TrimSpace(fmt.Sprint(raw))
	if raw == nil || text == "" || runningHubMediaLabels[param.Use] != "" {
		return nil, false
	}
	switch param.Type {
	case "LIST", "SIZE":
		value := runningHubOption(param, func(option string) (float64, bool) { return 0, option == text })
		return value, value != nil
	case "BOOLEAN":
		value, err := strconv.ParseBool(text)
		return value, err == nil
	case "INT", "FLOAT":
		number, err := strconv.ParseFloat(text, 64)
		if err != nil {
			return nil, false
		}
		return runningHubNumberValue(param, number), true
	}
	return text, true
}

func runningHubParamValue(param runningHubParam, inputs RunningHubInputs, used map[string]int, sizedByPixels bool) any {
	width, height, hasDims := runningHubDims(inputs.Size)
	switch param.Use {
	case "prompt":
		if prompt := strings.TrimSpace(inputs.Prompt); prompt != "" {
			return prompt
		}
	case "first", "last", "images", "videos", "audios":
		items := inputs.Media[param.Use][min(used[param.Use], len(inputs.Media[param.Use])):]
		items = items[:min(len(items), max(param.Limit, 1))]
		if len(items) == 0 {
			return nil
		}
		used[param.Use] += len(items)
		urls := make([]string, len(items))
		for index, item := range items {
			urls[index] = item.URL
		}
		if param.Multiple {
			return urls
		}
		return urls[0]
	case "duration":
		if seconds, err := strconv.ParseFloat(strings.TrimSpace(inputs.Seconds), 64); err == nil {
			return runningHubNumberValue(param, seconds)
		}
	case "resolution":
		wanted := strings.TrimSuffix(strings.ToLower(strings.TrimSpace(inputs.Resolution)), "p")
		level := runningHubVideoLevel(wanted)
		return runningHubOption(param, func(option string) (float64, bool) {
			if strings.TrimSuffix(strings.ToLower(option), "p") == wanted {
				return -1, wanted != ""
			}
			optionLevel := runningHubVideoLevel(option)
			return math.Abs(math.Log(optionLevel / level)), optionLevel > 0 && level > 0
		})
	case "level":
		if sizedByPixels {
			return runningHubOption(param, func(option string) (float64, bool) { return 0, strings.EqualFold(option, "empty") })
		}
		if !hasDims {
			return nil
		}
		target := math.Max(width, height) / 1024
		return runningHubOption(param, func(option string) (float64, bool) {
			value, err := strconv.ParseFloat(strings.TrimSuffix(strings.ToLower(option), "k"), 64)
			return math.Abs(math.Log(value / target)), err == nil && value > 0 && strings.HasSuffix(strings.ToLower(option), "k")
		})
	case "ratio":
		return runningHubRatioOption(param, inputs.Size)
	case "size":
		ratio, hasRatio := runningHubRatio(inputs.Size)
		level := runningHubVideoLevel(inputs.Resolution)
		if level == 0 && hasDims {
			level = math.Sqrt(width * height * 9 / 16)
		}
		if !hasRatio && level == 0 {
			return nil
		}
		return runningHubOption(param, func(option string) (float64, bool) {
			optionWidth, optionHeight, ok := runningHubDims(option)
			score := 0.0
			if hasRatio {
				score += 4 * math.Abs(math.Log(optionWidth/optionHeight/ratio))
			}
			if level > 0 {
				score += math.Abs(math.Log(math.Sqrt(optionWidth*optionHeight*9/16) / level))
			}
			return score, ok
		})
	case "width", "height":
		if hasDims && param.Use == "width" {
			return runningHubNumberValue(param, width)
		}
		if hasDims {
			return runningHubNumberValue(param, height)
		}
	case "quality", "voice":
		value := inputs.Quality
		if param.Use == "voice" {
			value = inputs.Voice
		}
		value = strings.TrimSpace(value)
		if value == "" {
			return nil
		}
		if param.Type != "LIST" {
			return value
		}
		return runningHubOption(param, func(option string) (float64, bool) { return 0, strings.EqualFold(option, value) })
	case "audio":
		enabled, err := strconv.ParseBool(strings.TrimSpace(inputs.GenerateAudio))
		if err != nil {
			return nil
		}
		if param.Type == "BOOLEAN" {
			return enabled
		}
		return runningHubOption(param, func(option string) (float64, bool) { return 0, strings.EqualFold(option, strconv.FormatBool(enabled)) })
	case "count":
		if inputs.Count > 0 {
			return runningHubNumberValue(param, float64(inputs.Count))
		}
	case "speed":
		if inputs.Speed > 0 {
			return runningHubNumberValue(param, inputs.Speed)
		}
	}
	return nil
}

// runningHubOption returns the LIST option with the lowest score; options the scorer rejects are skipped.
func runningHubOption(param runningHubParam, score func(option string) (float64, bool)) any {
	var best any
	bestScore := math.Inf(1)
	for _, option := range param.Options {
		if value, ok := score(strings.TrimSpace(fmt.Sprint(option))); ok && value < bestScore {
			best, bestScore = option, value
		}
	}
	return best
}

// runningHubNumberValue snaps a number to the nearest LIST option, or clamps it to the INT/FLOAT range.
func runningHubNumberValue(param runningHubParam, value float64) any {
	if param.Type == "LIST" {
		return runningHubOption(param, func(option string) (float64, bool) {
			number, err := strconv.ParseFloat(option, 64)
			return math.Abs(number - value), err == nil
		})
	}
	if param.Min != nil {
		value = math.Max(value, *param.Min)
	}
	if param.Max != nil {
		value = math.Min(value, *param.Max)
	}
	if param.Type != "INT" {
		return value
	}
	if param.Step != nil && *param.Step > 1 {
		base, step := 0.0, *param.Step
		if param.Min != nil {
			base = *param.Min
		}
		value = base + math.Round((value-base)/step)*step
	}
	return int(math.Round(value))
}

func runningHubRatioOption(param runningHubParam, size string) any {
	size = strings.ToLower(strings.TrimSpace(size))
	if size == "" {
		return nil
	}
	target, ok := runningHubRatio(size)
	return runningHubOption(param, func(option string) (float64, bool) {
		if !ok {
			option = strings.ToLower(option)
			if option == size {
				return 0, true
			}
			return 1, option == "adaptive" || option == "auto" || option == "empty"
		}
		value, valid := runningHubRatio(option)
		return math.Abs(math.Log(value / target)), valid
	})
}

func runningHubRatio(value string) (float64, bool) {
	if width, height, ok := runningHubDims(value); ok {
		return width / height, true
	}
	left, right, found := strings.Cut(strings.TrimSpace(value), ":")
	width, widthErr := strconv.ParseFloat(left, 64)
	height, heightErr := strconv.ParseFloat(right, 64)
	return width / height, found && widthErr == nil && heightErr == nil && width > 0 && height > 0
}

func runningHubDims(value string) (float64, float64, bool) {
	left, right, found := strings.Cut(strings.ReplaceAll(strings.ToLower(strings.TrimSpace(value)), "*", "x"), "x")
	width, widthErr := strconv.ParseFloat(strings.TrimSpace(left), 64)
	height, heightErr := strconv.ParseFloat(strings.TrimSpace(right), 64)
	return width, height, found && widthErr == nil && heightErr == nil && width > 0 && height > 0
}

// runningHubVideoLevel converts 720p, 2K, fhd or native1080p style labels to a short-edge pixel level.
func runningHubVideoLevel(value string) float64 {
	value = strings.TrimPrefix(strings.ToLower(strings.TrimSpace(value)), "native")
	switch value {
	case "hd":
		return 720
	case "fhd":
		return 1080
	case "2k":
		return 1440
	case "4k":
		return 2160
	}
	number, _ := strconv.ParseFloat(strings.TrimSuffix(value, "p"), 64)
	return number
}

// ParseRunningHubTask normalizes a submit or query response; ok is false when the payload is not a RunningHub task.
func ParseRunningHubTask(payload []byte) (RunningHubTask, bool) {
	var root struct {
		TaskID       json.RawMessage  `json:"taskId"`
		Status       string           `json:"status"`
		ErrorCode    json.RawMessage  `json:"errorCode"`
		ErrorMessage string           `json:"errorMessage"`
		Code         json.RawMessage  `json:"code"`
		Message      string           `json:"message"`
		Msg          string           `json:"msg"`
		Results      []map[string]any `json:"results"`
	}
	if json.Unmarshal(payload, &root) != nil {
		return RunningHubTask{Raw: payload}, false
	}
	text := func(raw json.RawMessage) string {
		value := strings.Trim(strings.TrimSpace(string(raw)), `"`)
		if value == "0" || value == "null" {
			return ""
		}
		return value
	}
	task := RunningHubTask{TaskID: text(root.TaskID), Status: NormalizeVideoTaskStatus(root.Status), Raw: payload}
	for _, result := range root.Results {
		for _, key := range []string{"url", "outputUrl", "text", "content", "output"} {
			value := runningHubResultText(result[key])
			if strings.HasPrefix(value, "http://") || strings.HasPrefix(value, "https://") {
				task.URLs = append(task.URLs, value)
				break
			}
			if value != "" && key != "url" && key != "outputUrl" {
				if task.Text == "" {
					task.Text = value
				}
				task.Texts = append(task.Texts, value)
				break
			}
		}
	}
	switch errorCode := firstVideoTaskValue(text(root.ErrorCode), text(root.Code)); {
	case root.ErrorMessage != "" || errorCode != "":
		task.Status, task.Error = "failed", firstVideoTaskValue(root.ErrorMessage, root.Message, root.Msg, "RunningHub 错误码 "+errorCode)
	case task.Status == "failed":
		task.Error = "RunningHub 任务失败或已取消"
	case task.Status == "completed" && len(task.URLs) == 0 && task.Text == "":
		task.Status, task.Error = "failed", "RunningHub 任务完成但没有返回结果"
	}
	return task, task.TaskID != "" || root.Status != "" || task.Error != ""
}

func runningHubResultText(value any) string {
	if text, ok := value.(string); ok || value == nil {
		return strings.TrimSpace(text)
	}
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

// NewRunningHubQueryRequest builds the authenticated POST {base}/query request for a task.
func NewRunningHubQueryRequest(channel model.ModelChannel, taskID string) (*http.Request, error) {
	body, _ := json.Marshal(map[string]string{"taskId": taskID})
	request, err := http.NewRequest(http.MethodPost, BuildModelChannelURL(channel, "/query"), bytes.NewReader(body))
	if err == nil {
		SetModelChannelAuthHeader(request, channel)
		request.Header.Set("Content-Type", "application/json")
	}
	return request, err
}

// WaitRunningHubTask polls the task submitted with payload until it finishes or the channel timeout elapses.
func WaitRunningHubTask(channel model.ModelChannel, payload []byte) (RunningHubTask, error) {
	task, _ := ParseRunningHubTask(payload)
	taskID, deadline, failures := task.TaskID, time.Now().Add(ChannelTimeout(channel)), 0
	for {
		switch {
		case task.Status == "failed":
			return task, errors.New(task.Error)
		case task.Status == "completed":
			return task, nil
		case taskID == "":
			return task, errors.New("RunningHub 没有返回任务 ID")
		case time.Now().After(deadline):
			return task, fmt.Errorf("RunningHub 任务 %s 等待超时，可稍后在 RunningHub 调用记录中查看结果", taskID)
		}
		time.Sleep(runningHubPollInterval)
		next, status, err := doRunningHubQuery(channel, taskID)
		parsed, ok := ParseRunningHubTask(next)
		switch {
		case err == nil && status < http.StatusBadRequest && ok:
			task, failures = parsed, 0
		case err == nil && status >= http.StatusBadRequest && status < http.StatusInternalServerError && status != http.StatusTooManyRequests:
			return parsed, errors.New(firstVideoTaskValue(parsed.Error, fmt.Sprintf("RunningHub 任务查询失败：%d", status)))
		default:
			if failures++; failures >= 5 {
				return task, fmt.Errorf("RunningHub 任务 %s 查询失败，可稍后在 RunningHub 调用记录中查看结果", taskID)
			}
		}
	}
}

func doRunningHubQuery(channel model.ModelChannel, taskID string) ([]byte, int, error) {
	request, err := NewRunningHubQueryRequest(channel, taskID)
	if err != nil {
		return nil, 0, err
	}
	response, err := HTTPClientForChannel(channel).Do(request)
	if err != nil {
		return nil, 0, err
	}
	defer response.Body.Close()
	payload, err := io.ReadAll(io.LimitReader(response.Body, 1<<20))
	return payload, response.StatusCode, err
}

// UploadRunningHubMedia returns a URL RunningHub can read: http(s) URLs pass through, files and data URLs go to /media/upload/binary.
func UploadRunningHubMedia(channel model.ModelChannel, media RunningHubMedia) (string, error) {
	if len(media.Data) == 0 {
		value := strings.TrimSpace(media.URL)
		if strings.HasPrefix(value, "http://") || strings.HasPrefix(value, "https://") {
			return value, nil
		}
		meta, data, found := strings.Cut(strings.TrimPrefix(value, "data:"), ",")
		decoded, err := base64.StdEncoding.DecodeString(data)
		if !strings.HasPrefix(value, "data:") || !found || !strings.HasSuffix(meta, ";base64") || err != nil || len(decoded) == 0 {
			return "", errors.New("参考素材地址无效，请使用公网 URL 或本地文件")
		}
		media.Data, media.ContentType = decoded, strings.TrimSuffix(meta, ";base64")
	}
	if media.Filename == "" {
		extension := strings.TrimPrefix(media.ContentType[strings.Index(media.ContentType, "/")+1:], "x-")
		media.Filename = "upload." + firstVideoTaskValue(map[string]string{"jpeg": "jpg", "mpeg": "mp3", "quicktime": "mov"}[extension], extension, "bin")
	}
	var body bytes.Buffer
	writer := multipart.NewWriter(&body)
	header := textproto.MIMEHeader{}
	header.Set("Content-Disposition", mime.FormatMediaType("form-data", map[string]string{"name": "file", "filename": media.Filename}))
	header.Set("Content-Type", firstVideoTaskValue(media.ContentType, "application/octet-stream"))
	part, err := writer.CreatePart(header)
	if err == nil {
		_, err = part.Write(media.Data)
	}
	if err == nil {
		err = writer.Close()
	}
	var request *http.Request
	if err == nil {
		request, err = http.NewRequest(http.MethodPost, BuildModelChannelURL(channel, "/media/upload/binary"), &body)
	}
	if err != nil {
		return "", fmt.Errorf("RunningHub 素材上传失败：%v", err)
	}
	SetModelChannelAuthHeader(request, channel)
	request.Header.Set("Content-Type", writer.FormDataContentType())
	response, err := HTTPClientForChannel(channel).Do(request)
	if err != nil {
		return "", fmt.Errorf("RunningHub 素材上传失败：%v", err)
	}
	defer response.Body.Close()
	payload, _ := io.ReadAll(io.LimitReader(response.Body, 1<<20))
	var result struct {
		Message string `json:"message"`
		Msg     string `json:"msg"`
		Data    struct {
			DownloadURL string `json:"download_url"`
		} `json:"data"`
	}
	if json.Unmarshal(payload, &result) != nil || response.StatusCode >= http.StatusBadRequest || result.Data.DownloadURL == "" {
		return "", fmt.Errorf("RunningHub 素材上传失败：%s", firstVideoTaskValue(result.Message, result.Msg, strconv.Itoa(response.StatusCode)))
	}
	return result.Data.DownloadURL, nil
}

// RunningHubResultURL picks the preferred result file for an output kind ("audio" or "model3d"), else the first URL.
func RunningHubResultURL(urls []string, kind string) string {
	for _, extension := range runningHubResultExtensions[kind] {
		for _, url := range urls {
			if strings.EqualFold(path.Ext(strings.Split(url, "?")[0]), extension) {
				return url
			}
		}
	}
	return urls[0]
}

// DownloadRunningHubResult fetches a result file, such as TTS audio returned by the proxy as bytes.
func DownloadRunningHubResult(url string) ([]byte, string, error) {
	response, err := SafeProxyHTTPClient().Get(url)
	if err != nil {
		return nil, "", fmt.Errorf("RunningHub 结果下载失败：%v", err)
	}
	defer response.Body.Close()
	if response.StatusCode >= http.StatusBadRequest {
		return nil, "", fmt.Errorf("RunningHub 结果下载失败：%d", response.StatusCode)
	}
	data, err := io.ReadAll(io.LimitReader(response.Body, 32<<20))
	contentType := strings.TrimSpace(strings.Split(response.Header.Get("Content-Type"), ";")[0])
	if !strings.HasPrefix(contentType, "audio/") {
		contentType = http.DetectContentType(data)
	}
	return data, contentType, err
}

// runningHubDownload fetches result files; tests replace it because the safe proxy client bypasses mocked transports.
var runningHubDownload = DownloadRunningHubResult

// runningHubAudioDurationMs measures an MP3 (MPEG Layer III frames, optional ID3v2 tag) or WAV file, returning 0 otherwise.
func runningHubAudioDurationMs(data []byte) int {
	if len(data) >= 12 && string(data[:4]) == "RIFF" && string(data[8:12]) == "WAVE" {
		byteRate, dataSize := 0, 0
		for offset := 12; offset+8 <= len(data); {
			size := int(binary.LittleEndian.Uint32(data[offset+4 : offset+8]))
			switch string(data[offset : offset+4]) {
			case "fmt ":
				if offset+20 <= len(data) {
					byteRate = int(binary.LittleEndian.Uint32(data[offset+16 : offset+20]))
				}
			case "data":
				dataSize = min(size, len(data)-offset-8)
			}
			offset += 8 + size + size%2
		}
		if byteRate == 0 {
			return 0
		}
		return dataSize * 1000 / byteRate
	}
	offset := 0
	if len(data) >= 10 && string(data[:3]) == "ID3" {
		offset = 10 + (int(data[6]&0x7f)<<21 | int(data[7]&0x7f)<<14 | int(data[8]&0x7f)<<7 | int(data[9]&0x7f))
	}
	samples, sampleRate := 0, 0
	for offset+4 <= len(data) {
		b1, b2 := data[offset+1], data[offset+2]
		version, layer, bitrateIndex, rateIndex := b1>>3&3, b1>>1&3, int(b2>>4), int(b2>>2&3)
		if data[offset] != 0xFF || b1&0xE0 != 0xE0 || version == 1 || layer != 1 || bitrateIndex == 0 || bitrateIndex == 15 || rateIndex == 3 {
			offset++
			continue
		}
		rate, bitrate, frameSamples, slot := [3]int{44100, 48000, 32000}[rateIndex], [15]int{0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320}[bitrateIndex], 1152, 144
		if version != 3 { // MPEG-2 halves the sample rate, MPEG-2.5 quarters it
			rate, bitrate, frameSamples, slot = rate/2, [15]int{0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144, 160}[bitrateIndex], 576, 72
			if version == 0 {
				rate /= 2
			}
		}
		samples, sampleRate = samples+frameSamples, rate
		offset += slot*bitrate*1000/rate + int(b2>>1&1)
	}
	if sampleRate == 0 {
		return 0
	}
	return samples * 1000 / sampleRate
}

// runRunningHubTask submits one endpoint request and waits for its result.
func runRunningHubTask(channel model.ModelChannel, endpoint string, inputs RunningHubInputs) (RunningHubTask, error) {
	body, err := BuildRunningHubPayload(endpoint, inputs)
	if err != nil {
		return RunningHubTask{}, err
	}
	request, err := http.NewRequest(http.MethodPost, BuildModelChannelURL(channel, "/"+endpoint), bytes.NewReader(body))
	if err != nil {
		return RunningHubTask{}, err
	}
	SetModelChannelAuthHeader(request, channel)
	request.Header.Set("Content-Type", "application/json")
	response, err := HTTPClientForChannel(channel).Do(request)
	if err != nil {
		return RunningHubTask{}, err
	}
	defer response.Body.Close()
	payload, _ := io.ReadAll(io.LimitReader(response.Body, 1<<20))
	if response.StatusCode >= http.StatusBadRequest {
		task, _ := ParseRunningHubTask(payload)
		return task, errors.New(firstVideoTaskValue(task.Error, fmt.Sprintf("RunningHub 请求失败：%d", response.StatusCode)))
	}
	return WaitRunningHubTask(channel, payload)
}

// PrepareRunningHubLipSync identifies the face in the reference video, synthesizes speech with Kling TTS when no
// reference audio is given, and returns the lip-sync-video submit body for the shared video task flow. Audio without a
// known duration is downloaded and measured.
func PrepareRunningHubLipSync(channel model.ModelChannel, inputs RunningHubInputs) ([]byte, error) {
	videos, audios := inputs.Media["videos"], inputs.Media["audios"]
	if len(videos) == 0 {
		return nil, errors.New("该模型需要参考视频")
	}
	if len(audios) == 0 && strings.TrimSpace(inputs.Prompt) == "" {
		return nil, errors.New("请连接参考音频，或输入要朗读的文本")
	}
	face, err := runRunningHubTask(channel, "kling-lip-sync/identify-face", RunningHubInputs{Media: map[string][]RunningHubMedia{"videos": videos[:1]}})
	if err != nil {
		return nil, fmt.Errorf("人脸识别失败：%w", err)
	}
	faceFacts := runningHubTaskFacts(face)
	if faceFacts["sessionid"] == "" || faceFacts["faceid"] == "" {
		return nil, errors.New("参考视频中没有识别到可对口型的人脸")
	}
	extra := map[string]any{}
	for key, value := range inputs.Extra {
		extra[key] = value
	}
	insertMs, _ := strconv.Atoi(faceFacts["starttime"])
	extra["sessionId"], extra["faceId"], extra["soundStartTime"], extra["soundInsertTime"] = faceFacts["sessionid"], faceFacts["faceid"], 0, insertMs
	lipSync := RunningHubInputs{Extra: extra, Media: map[string][]RunningHubMedia{"audios": audios}}
	durationMs := inputs.AudioDurationMs
	if len(audios) == 0 {
		speech, err := runRunningHubTask(channel, "kling-lip-sync/tts", RunningHubInputs{Prompt: inputs.Prompt, Extra: inputs.Extra})
		if err != nil {
			return nil, fmt.Errorf("口型配音生成失败：%w", err)
		}
		// Kling TTS returns the MP3 and a bare audio ID without its duration, so the MP3 is measured below.
		speechURL := RunningHubResultURL(speech.URLs, "audio")
		if speechURL == "" {
			return nil, errors.New("口型配音没有返回音频")
		}
		lipSync.Media["audios"], durationMs = []RunningHubMedia{{URL: speechURL}}, 0
	}
	if durationMs <= 0 {
		if data, _, err := runningHubDownload(lipSync.Media["audios"][0].URL); err == nil {
			durationMs = runningHubAudioDurationMs(data)
		}
	}
	if durationMs <= 0 {
		return nil, errors.New("无法获取音频时长，请重新连接参考音频节点")
	}
	// The dubbed span has to stay inside the detected face window.
	if faceEnd, err := strconv.Atoi(faceFacts["endtime"]); err == nil && faceEnd > insertMs {
		durationMs = min(durationMs, faceEnd-insertMs)
	}
	extra["soundEndTime"] = durationMs
	return BuildRunningHubPayload("kling-lip-sync/lip-sync-video", lipSync)
}

// runningHubTaskFacts merges the JSON facts of every text result; earlier results win.
func runningHubTaskFacts(task RunningHubTask) map[string]string {
	facts := map[string]string{}
	for _, text := range task.Texts {
		for key, value := range runningHubJSONFacts(text) {
			if _, seen := facts[key]; !seen {
				facts[key] = value
			}
		}
	}
	return facts
}

// runningHubJSONFacts collects the first scalar per key from a JSON text result, keyed in lower case without underscores.
// Shallower values win over nested ones.
func runningHubJSONFacts(text string) map[string]string {
	facts := map[string]string{}
	decode := func(value string) (any, bool) {
		var root any
		decoder := json.NewDecoder(strings.NewReader(value))
		decoder.UseNumber()
		return root, decoder.Decode(&root) == nil
	}
	root, ok := decode(text)
	if nested, isString := root.(string); ok && isString {
		root, ok = decode(nested)
	}
	if !ok {
		return facts
	}
	queue := []any{root}
	for len(queue) > 0 {
		node := queue[0]
		queue = queue[1:]
		switch typed := node.(type) {
		case map[string]any:
			keys := make([]string, 0, len(typed))
			for key := range typed {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			for _, key := range keys {
				name := strings.ToLower(strings.ReplaceAll(key, "_", ""))
				switch value := typed[key].(type) {
				case string, json.Number, bool:
					if _, seen := facts[name]; !seen {
						facts[name] = strings.TrimSpace(fmt.Sprint(value))
					}
				default:
					queue = append(queue, value)
				}
			}
		case []any:
			queue = append(queue, typed...)
		}
	}
	return facts
}
