package service

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"mime"
	"mime/multipart"
	"net/http"
	"net/textproto"
	"path"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/tigerowo/infinite-canvas/model"
)

const ModelChannelProtocolRunningHub = "runninghub"

// runninghub_registry.json is generated by scripts/runninghub-registry.mjs from the official RunningHub model registry.
//
//go:embed runninghub_registry.json
var runningHubRegistryJSON []byte

var runningHubMediaLabels = map[string]string{"first": "首帧", "last": "尾帧", "images": "参考图", "videos": "参考视频", "audios": "参考音频"}

// runningHubPollInterval follows the RunningHub API contract's 5-second polling guidance.
var runningHubPollInterval = 5 * time.Second

type runningHubParam struct {
	Key      string   `json:"key"`
	Type     string   `json:"type"`
	Use      string   `json:"use"`
	Required bool     `json:"required"`
	Default  any      `json:"default"`
	Options  []any    `json:"options"`
	Min      *float64 `json:"min"`
	Max      *float64 `json:"max"`
	Step     *float64 `json:"step"`
	Limit    int      `json:"limit"`
	Multiple bool     `json:"multiple"`
}

type runningHubRegistryData struct {
	// Families maps `<family>/video|image|tts` to input modes and their candidate endpoints in preference order.
	Families  map[string]map[string][]string `json:"families"`
	Endpoints map[string][]runningHubParam   `json:"endpoints"`
}

var runningHubRegistry = sync.OnceValue(func() runningHubRegistryData {
	var registry runningHubRegistryData
	if err := json.Unmarshal(runningHubRegistryJSON, &registry); err != nil {
		panic("invalid RunningHub registry: " + err.Error())
	}
	return registry
})

// RunningHubMedia is one request input: a URL, or file bytes that are uploaded to RunningHub first.
type RunningHubMedia struct {
	URL         string
	Data        []byte
	Filename    string
	ContentType string
}

// RunningHubInputs are the OpenAI-shaped request values mapped onto a RunningHub endpoint schema.
type RunningHubInputs struct {
	Prompt        string
	Size          string // ratio such as 16:9 or adaptive, or WxH pixels
	Resolution    string // video level such as 720p or 2k
	Quality       string
	Seconds       string
	GenerateAudio string
	Voice         string
	Count         int
	Speed         float64
	Media         map[string][]RunningHubMedia // keyed by runningHubMediaLabels roles
}

type RunningHubTask struct {
	TaskID string
	Status string // queued, processing, completed or failed
	URLs   []string
	Error  string
	Raw    []byte
}

func IsRunningHubChannel(channel model.ModelChannel) bool {
	return strings.EqualFold(strings.TrimSpace(channel.Protocol), ModelChannelProtocolRunningHub)
}

func RunningHubModels() []string {
	models := make([]string, 0, len(runningHubRegistry().Families))
	for name := range runningHubRegistry().Families {
		models = append(models, name)
	}
	sort.Strings(models)
	return models
}

func runningHubBaseURL(channel model.ModelChannel) string {
	baseURL := normalizeModelChannelBaseURL(channel.BaseURL)
	if !strings.HasSuffix(strings.ToLower(baseURL), "/openapi/v2") {
		baseURL += "/openapi/v2"
	}
	return baseURL
}

// SelectRunningHubEndpoint picks the first family endpoint for the input mode whose media fields accept every input.
func SelectRunningHubEndpoint(modelName string, media map[string][]RunningHubMedia) (string, error) {
	modelName = strings.TrimSpace(modelName)
	modes, ok := runningHubRegistry().Families[modelName]
	if !ok {
		return "", fmt.Errorf("RunningHub 暂不支持模型 %s", modelName)
	}
	mode := "text"
	switch {
	case len(media["first"])+len(media["last"]) > 0:
		mode = "frames"
	case strings.HasSuffix(modelName, "/image") && len(media["images"]) > 0:
		mode = "edit"
	case len(media["images"])+len(media["videos"])+len(media["audios"]) > 0:
		mode = "reference"
	}
	for _, endpoint := range modes[mode] {
		if runningHubEndpointFits(runningHubRegistry().Endpoints[endpoint], media) {
			return endpoint, nil
		}
	}
	// Name the missing required media: of the chosen mode, or of any mode when only a prompt was given.
	candidates := modes[mode]
	if mode == "text" {
		candidates = append(append(append([]string{}, modes["frames"]...), modes["reference"]...), modes["edit"]...)
	}
	for _, endpoint := range candidates {
		for _, param := range runningHubRegistry().Endpoints[endpoint] {
			if label := runningHubMediaLabels[param.Use]; label != "" && param.Required && len(media[param.Use]) == 0 {
				return "", errors.New("该模型需要" + label)
			}
		}
	}
	if len(modes[mode]) > 0 {
		return "", fmt.Errorf("素材数量或组合不符合该模型要求：首帧 %d、尾帧 %d、参考图 %d、参考视频 %d、参考音频 %d", len(media["first"]), len(media["last"]), len(media["images"]), len(media["videos"]), len(media["audios"]))
	}
	return "", errors.New(map[string]string{"text": "该模型不支持纯文本生成，请添加首帧或参考素材", "frames": "该模型不支持首尾帧", "reference": "该模型不支持参考素材", "edit": "该模型不支持参考图"}[mode])
}

func runningHubEndpointFits(params []runningHubParam, media map[string][]RunningHubMedia) bool {
	capacity := map[string]int{}
	for _, param := range params {
		if runningHubMediaLabels[param.Use] == "" {
			continue
		}
		if param.Required && len(media[param.Use]) == 0 {
			return false
		}
		capacity[param.Use] += max(param.Limit, 1)
	}
	for use, items := range media {
		if len(items) > capacity[use] {
			return false
		}
	}
	return true
}

// BuildRunningHubPayload maps inputs onto the endpoint schema; required fields without an input use the schema default.
func BuildRunningHubPayload(endpoint string, inputs RunningHubInputs) ([]byte, error) {
	params := runningHubRegistry().Endpoints[endpoint]
	payload := map[string]any{}
	used := map[string]int{}
	_, _, hasDims := runningHubDims(inputs.Size)
	sizedByPixels := false
	for _, param := range params {
		sizedByPixels = sizedByPixels || hasDims && param.Use == "width"
	}
	for _, param := range params {
		if param.Use == "prompt" && param.Required && strings.TrimSpace(inputs.Prompt) == "" {
			return nil, errors.New("请输入提示词")
		}
		value := runningHubParamValue(param, inputs, used, sizedByPixels)
		if value == nil && param.Required {
			value = param.Default
		}
		if value == nil {
			if param.Required {
				return nil, fmt.Errorf("RunningHub 缺少参数 %s", param.Key)
			}
			continue
		}
		payload[param.Key] = value
	}
	return json.Marshal(payload)
}

func runningHubParamValue(param runningHubParam, inputs RunningHubInputs, used map[string]int, sizedByPixels bool) any {
	width, height, hasDims := runningHubDims(inputs.Size)
	switch param.Use {
	case "prompt":
		if prompt := strings.TrimSpace(inputs.Prompt); prompt != "" {
			return prompt
		}
	case "first", "last", "images", "videos", "audios":
		items := inputs.Media[param.Use][min(used[param.Use], len(inputs.Media[param.Use])):]
		items = items[:min(len(items), max(param.Limit, 1))]
		if len(items) == 0 {
			return nil
		}
		used[param.Use] += len(items)
		urls := make([]string, len(items))
		for index, item := range items {
			urls[index] = item.URL
		}
		if param.Multiple {
			return urls
		}
		return urls[0]
	case "duration":
		if seconds, err := strconv.ParseFloat(strings.TrimSpace(inputs.Seconds), 64); err == nil {
			return runningHubNumberValue(param, seconds)
		}
	case "resolution":
		wanted := strings.TrimSuffix(strings.ToLower(strings.TrimSpace(inputs.Resolution)), "p")
		level := runningHubVideoLevel(wanted)
		return runningHubOption(param, func(option string) (float64, bool) {
			if strings.TrimSuffix(strings.ToLower(option), "p") == wanted {
				return -1, wanted != ""
			}
			optionLevel := runningHubVideoLevel(option)
			return math.Abs(math.Log(optionLevel / level)), optionLevel > 0 && level > 0
		})
	case "level":
		if sizedByPixels {
			return runningHubOption(param, func(option string) (float64, bool) { return 0, strings.EqualFold(option, "empty") })
		}
		if !hasDims {
			return nil
		}
		target := math.Max(width, height) / 1024
		return runningHubOption(param, func(option string) (float64, bool) {
			value, err := strconv.ParseFloat(strings.TrimSuffix(strings.ToLower(option), "k"), 64)
			return math.Abs(math.Log(value / target)), err == nil && value > 0 && strings.HasSuffix(strings.ToLower(option), "k")
		})
	case "ratio":
		return runningHubRatioOption(param, inputs.Size)
	case "size":
		ratio, hasRatio := runningHubRatio(inputs.Size)
		level := runningHubVideoLevel(inputs.Resolution)
		if level == 0 && hasDims {
			level = math.Sqrt(width * height * 9 / 16)
		}
		if !hasRatio && level == 0 {
			return nil
		}
		return runningHubOption(param, func(option string) (float64, bool) {
			optionWidth, optionHeight, ok := runningHubDims(option)
			score := 0.0
			if hasRatio {
				score += 4 * math.Abs(math.Log(optionWidth/optionHeight/ratio))
			}
			if level > 0 {
				score += math.Abs(math.Log(math.Sqrt(optionWidth*optionHeight*9/16) / level))
			}
			return score, ok
		})
	case "width", "height":
		if hasDims && param.Use == "width" {
			return runningHubNumberValue(param, width)
		}
		if hasDims {
			return runningHubNumberValue(param, height)
		}
	case "quality", "voice":
		value := inputs.Quality
		if param.Use == "voice" {
			value = inputs.Voice
		}
		value = strings.TrimSpace(value)
		if value == "" {
			return nil
		}
		if param.Type != "LIST" {
			return value
		}
		return runningHubOption(param, func(option string) (float64, bool) { return 0, strings.EqualFold(option, value) })
	case "audio":
		enabled, err := strconv.ParseBool(strings.TrimSpace(inputs.GenerateAudio))
		if err != nil {
			return nil
		}
		if param.Type == "BOOLEAN" {
			return enabled
		}
		return runningHubOption(param, func(option string) (float64, bool) { return 0, strings.EqualFold(option, strconv.FormatBool(enabled)) })
	case "count":
		if inputs.Count > 0 {
			return runningHubNumberValue(param, float64(inputs.Count))
		}
	case "speed":
		if inputs.Speed > 0 {
			return runningHubNumberValue(param, inputs.Speed)
		}
	}
	return nil
}

// runningHubOption returns the LIST option with the lowest score; options the scorer rejects are skipped.
func runningHubOption(param runningHubParam, score func(option string) (float64, bool)) any {
	var best any
	bestScore := math.Inf(1)
	for _, option := range param.Options {
		if value, ok := score(strings.TrimSpace(fmt.Sprint(option))); ok && value < bestScore {
			best, bestScore = option, value
		}
	}
	return best
}

// runningHubNumberValue snaps a number to the nearest LIST option, or clamps it to the INT/FLOAT range.
func runningHubNumberValue(param runningHubParam, value float64) any {
	if param.Type == "LIST" {
		return runningHubOption(param, func(option string) (float64, bool) {
			number, err := strconv.ParseFloat(option, 64)
			return math.Abs(number - value), err == nil
		})
	}
	if param.Min != nil {
		value = math.Max(value, *param.Min)
	}
	if param.Max != nil {
		value = math.Min(value, *param.Max)
	}
	if param.Type != "INT" {
		return value
	}
	if param.Step != nil && *param.Step > 1 {
		base, step := 0.0, *param.Step
		if param.Min != nil {
			base = *param.Min
		}
		value = base + math.Round((value-base)/step)*step
	}
	return int(math.Round(value))
}

func runningHubRatioOption(param runningHubParam, size string) any {
	size = strings.ToLower(strings.TrimSpace(size))
	if size == "" {
		return nil
	}
	target, ok := runningHubRatio(size)
	return runningHubOption(param, func(option string) (float64, bool) {
		if !ok {
			option = strings.ToLower(option)
			if option == size {
				return 0, true
			}
			return 1, option == "adaptive" || option == "auto" || option == "empty"
		}
		value, valid := runningHubRatio(option)
		return math.Abs(math.Log(value / target)), valid
	})
}

func runningHubRatio(value string) (float64, bool) {
	if width, height, ok := runningHubDims(value); ok {
		return width / height, true
	}
	left, right, found := strings.Cut(strings.TrimSpace(value), ":")
	width, widthErr := strconv.ParseFloat(left, 64)
	height, heightErr := strconv.ParseFloat(right, 64)
	return width / height, found && widthErr == nil && heightErr == nil && width > 0 && height > 0
}

func runningHubDims(value string) (float64, float64, bool) {
	left, right, found := strings.Cut(strings.ReplaceAll(strings.ToLower(strings.TrimSpace(value)), "*", "x"), "x")
	width, widthErr := strconv.ParseFloat(strings.TrimSpace(left), 64)
	height, heightErr := strconv.ParseFloat(strings.TrimSpace(right), 64)
	return width, height, found && widthErr == nil && heightErr == nil && width > 0 && height > 0
}

// runningHubVideoLevel converts 720p, 2K, fhd or native1080p style labels to a short-edge pixel level.
func runningHubVideoLevel(value string) float64 {
	value = strings.TrimPrefix(strings.ToLower(strings.TrimSpace(value)), "native")
	switch value {
	case "hd":
		return 720
	case "fhd":
		return 1080
	case "2k":
		return 1440
	case "4k":
		return 2160
	}
	number, _ := strconv.ParseFloat(strings.TrimSuffix(value, "p"), 64)
	return number
}

// ParseRunningHubTask normalizes a submit or query response; ok is false when the payload is not a RunningHub task.
func ParseRunningHubTask(payload []byte) (RunningHubTask, bool) {
	var root struct {
		TaskID       json.RawMessage  `json:"taskId"`
		Status       string           `json:"status"`
		ErrorCode    json.RawMessage  `json:"errorCode"`
		ErrorMessage string           `json:"errorMessage"`
		Code         json.RawMessage  `json:"code"`
		Message      string           `json:"message"`
		Msg          string           `json:"msg"`
		Results      []map[string]any `json:"results"`
	}
	if json.Unmarshal(payload, &root) != nil {
		return RunningHubTask{Raw: payload}, false
	}
	text := func(raw json.RawMessage) string {
		value := strings.Trim(strings.TrimSpace(string(raw)), `"`)
		if value == "0" || value == "null" {
			return ""
		}
		return value
	}
	task := RunningHubTask{TaskID: text(root.TaskID), Status: NormalizeVideoTaskStatus(root.Status), Raw: payload}
	for _, result := range root.Results {
		for _, key := range []string{"url", "outputUrl", "text", "content", "output"} {
			if value := strings.TrimSpace(fmt.Sprint(result[key])); strings.HasPrefix(value, "http://") || strings.HasPrefix(value, "https://") {
				task.URLs = append(task.URLs, value)
				break
			}
		}
	}
	switch errorCode := firstVideoTaskValue(text(root.ErrorCode), text(root.Code)); {
	case root.ErrorMessage != "" || errorCode != "":
		task.Status, task.Error = "failed", firstVideoTaskValue(root.ErrorMessage, root.Message, root.Msg, "RunningHub 错误码 "+errorCode)
	case task.Status == "failed":
		task.Error = "RunningHub 任务失败或已取消"
	case task.Status == "completed" && len(task.URLs) == 0:
		task.Status, task.Error = "failed", "RunningHub 任务完成但没有返回结果"
	}
	return task, task.TaskID != "" || root.Status != "" || task.Error != ""
}

// NewRunningHubQueryRequest builds the authenticated POST {base}/query request for a task.
func NewRunningHubQueryRequest(channel model.ModelChannel, taskID string) (*http.Request, error) {
	body, _ := json.Marshal(map[string]string{"taskId": taskID})
	request, err := http.NewRequest(http.MethodPost, BuildModelChannelURL(channel, "/query"), bytes.NewReader(body))
	if err == nil {
		SetModelChannelAuthHeader(request, channel)
		request.Header.Set("Content-Type", "application/json")
	}
	return request, err
}

// WaitRunningHubTask polls the task submitted with payload until it finishes or the channel timeout elapses.
func WaitRunningHubTask(channel model.ModelChannel, payload []byte) (RunningHubTask, error) {
	task, _ := ParseRunningHubTask(payload)
	taskID, deadline, failures := task.TaskID, time.Now().Add(ChannelTimeout(channel)), 0
	for {
		switch {
		case task.Status == "failed":
			return task, errors.New(task.Error)
		case task.Status == "completed":
			return task, nil
		case taskID == "":
			return task, errors.New("RunningHub 没有返回任务 ID")
		case time.Now().After(deadline):
			return task, fmt.Errorf("RunningHub 任务 %s 等待超时，可稍后在 RunningHub 调用记录中查看结果", taskID)
		}
		time.Sleep(runningHubPollInterval)
		next, status, err := doRunningHubQuery(channel, taskID)
		parsed, ok := ParseRunningHubTask(next)
		switch {
		case err == nil && status < http.StatusBadRequest && ok:
			task, failures = parsed, 0
		case err == nil && status >= http.StatusBadRequest && status < http.StatusInternalServerError && status != http.StatusTooManyRequests:
			return parsed, errors.New(firstVideoTaskValue(parsed.Error, fmt.Sprintf("RunningHub 任务查询失败：%d", status)))
		default:
			if failures++; failures >= 5 {
				return task, fmt.Errorf("RunningHub 任务 %s 查询失败，可稍后在 RunningHub 调用记录中查看结果", taskID)
			}
		}
	}
}

func doRunningHubQuery(channel model.ModelChannel, taskID string) ([]byte, int, error) {
	request, err := NewRunningHubQueryRequest(channel, taskID)
	if err != nil {
		return nil, 0, err
	}
	response, err := HTTPClientForChannel(channel).Do(request)
	if err != nil {
		return nil, 0, err
	}
	defer response.Body.Close()
	payload, err := io.ReadAll(io.LimitReader(response.Body, 1<<20))
	return payload, response.StatusCode, err
}

// UploadRunningHubMedia returns a URL RunningHub can read: http(s) URLs pass through, files and data URLs go to /media/upload/binary.
func UploadRunningHubMedia(channel model.ModelChannel, media RunningHubMedia) (string, error) {
	if len(media.Data) == 0 {
		value := strings.TrimSpace(media.URL)
		if strings.HasPrefix(value, "http://") || strings.HasPrefix(value, "https://") {
			return value, nil
		}
		meta, data, found := strings.Cut(strings.TrimPrefix(value, "data:"), ",")
		decoded, err := base64.StdEncoding.DecodeString(data)
		if !strings.HasPrefix(value, "data:") || !found || !strings.HasSuffix(meta, ";base64") || err != nil || len(decoded) == 0 {
			return "", errors.New("参考素材地址无效，请使用公网 URL 或本地文件")
		}
		media.Data, media.ContentType = decoded, strings.TrimSuffix(meta, ";base64")
	}
	if media.Filename == "" {
		extension := strings.TrimPrefix(media.ContentType[strings.Index(media.ContentType, "/")+1:], "x-")
		media.Filename = "upload." + firstVideoTaskValue(map[string]string{"jpeg": "jpg", "mpeg": "mp3", "quicktime": "mov"}[extension], extension, "bin")
	}
	var body bytes.Buffer
	writer := multipart.NewWriter(&body)
	header := textproto.MIMEHeader{}
	header.Set("Content-Disposition", mime.FormatMediaType("form-data", map[string]string{"name": "file", "filename": media.Filename}))
	header.Set("Content-Type", firstVideoTaskValue(media.ContentType, "application/octet-stream"))
	part, err := writer.CreatePart(header)
	if err == nil {
		_, err = part.Write(media.Data)
	}
	if err == nil {
		err = writer.Close()
	}
	var request *http.Request
	if err == nil {
		request, err = http.NewRequest(http.MethodPost, BuildModelChannelURL(channel, "/media/upload/binary"), &body)
	}
	if err != nil {
		return "", fmt.Errorf("RunningHub 素材上传失败：%v", err)
	}
	SetModelChannelAuthHeader(request, channel)
	request.Header.Set("Content-Type", writer.FormDataContentType())
	response, err := HTTPClientForChannel(channel).Do(request)
	if err != nil {
		return "", fmt.Errorf("RunningHub 素材上传失败：%v", err)
	}
	defer response.Body.Close()
	payload, _ := io.ReadAll(io.LimitReader(response.Body, 1<<20))
	var result struct {
		Message string `json:"message"`
		Msg     string `json:"msg"`
		Data    struct {
			DownloadURL string `json:"download_url"`
		} `json:"data"`
	}
	if json.Unmarshal(payload, &result) != nil || response.StatusCode >= http.StatusBadRequest || result.Data.DownloadURL == "" {
		return "", fmt.Errorf("RunningHub 素材上传失败：%s", firstVideoTaskValue(result.Message, result.Msg, strconv.Itoa(response.StatusCode)))
	}
	return result.Data.DownloadURL, nil
}

// RunningHubAudioURL picks the first audio result, since music tasks also return cover images.
func RunningHubAudioURL(urls []string) string {
	for _, url := range urls {
		switch strings.ToLower(path.Ext(strings.Split(url, "?")[0])) {
		case ".mp3", ".wav", ".flac", ".m4a", ".aac", ".ogg", ".opus":
			return url
		}
	}
	return urls[0]
}

// DownloadRunningHubResult fetches a result file, such as TTS audio returned by the proxy as bytes.
func DownloadRunningHubResult(url string) ([]byte, string, error) {
	response, err := SafeProxyHTTPClient().Get(url)
	if err != nil {
		return nil, "", fmt.Errorf("RunningHub 结果下载失败：%v", err)
	}
	defer response.Body.Close()
	if response.StatusCode >= http.StatusBadRequest {
		return nil, "", fmt.Errorf("RunningHub 结果下载失败：%d", response.StatusCode)
	}
	data, err := io.ReadAll(io.LimitReader(response.Body, 32<<20))
	contentType := strings.TrimSpace(strings.Split(response.Header.Get("Content-Type"), ";")[0])
	if !strings.HasPrefix(contentType, "audio/") {
		contentType = http.DetectContentType(data)
	}
	return data, contentType, err
}
